# To build and deploy to Cloud Run, run from this directory:
# $ gcloud builds submit . --config=cr-cloudbuild.yaml
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/pop-stats:$SHORT_SHA', 
  '-f', 'docker/pythonalpine.Dockerfile']
# Run unit tests
- name: gcr.io/$PROJECT_ID/pop-stats:$SHORT_SHA
  entrypoint: python
  args: ["unit_tests.py"]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pop-stats:$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'pop-stats', '--image', 'gcr.io/$PROJECT_ID/pop-stats:$SHORT_SHA', 
  '--region', 'us-west1', '--platform', 'managed', '--allow-unauthenticated']